# Primeros Pasos de Python#
## Cargar Modulos. Numpy

Python tiene definidos modulos que son conjuntos de funciones. Las funciones se acceden: modulo.funcion() 


In [24]:
# cargamos modulo
import numpy as np

In [9]:
## https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.math.html

In [2]:
# numpy es un paquete de números. 
np.sqrt(25)

5.0

In [7]:
# calculadora científica
np.sin(30)

-0.9880316240928618

In [3]:
# puede pasar listas a arrays. 
# las listas son para guardar variables no para operar con ellas. (Para hacer operaciones matemáticas hay que usar arrays. )
v=[1,2,3]
w=[5,4,2]
v+w

[1, 2, 3, 5, 4, 2]

In [6]:
v1=np.array(v)
w1=np.array(w)
print(type(v))
print(type(v1))
v1+w1  # me suma elemento a elemento los números del array

<class 'list'>
<class 'numpy.ndarray'>


array([6, 6, 5])

In [31]:
# numpy suele trabajar con array
a=np.zeros(10)
print(a)
a=np.ones(10)
print(a)
a=np.random.uniform(size=10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0.31322367 0.42770707 0.10835478 0.11587656 0.604673   0.04578005
 0.67793786 0.55069262 0.20339913 0.0416871 ]


In [16]:
# puede leer archivos
A=np.loadtxt('ejemplo.txt')
print('dimensiones de A',np.shape(A)) # shape nos da la dimension


dimensiones de A (9, 2)


In [32]:
# guardamos cada columna en un array. Numpy trabaja con arrays así que A es un array
print(type(A))
x=A[:,0]
y=A[:,1]

<class 'numpy.ndarray'>


In [ ]:
# guardamos un archivo
v=[1,2,3,4]
np.savetxt('nombreFichero.txt',v)

Ejercicios:
1. Genera una lista de 15 números, los que quieras
2. Guárdala en un fichero (con np.savetxt)
3. Lee el fichero (con np.loadtxt)
4. Escribe por pantalla la lista que has generado
5. Multiplica todos los elementos de la lista por 2. Comprueba que el resultado es el esperado. 
6. Escribe por pantalla el valor del elemento en la segunda posición.
7. Poned todos esos pasos en una función, dandole como parametros la lista y el nombre del archivo. 